language: node_js
node_js:
  - 4
  - 6
  - 7
  - stable

script: "npm run coverage"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"